removed the use of aurora-mdc-filter
Skatteetaten/aurora-spring-boot-mvc-starter pull request #21
Opened 2022-01-12 11:59 UTC by jarlehansen

2022-01-12 12:59 UTC, anderius approved these changes

2022-01-12 13:40 UTC, RuneOfferdal requested changes
Et par kommentarer.  Har satt request changes, så får du se om du er enig.

2022-01-12 13:40 UTC, RuneOfferdal commented on src/main/java/no/skatteetaten/aurora/mvc/AuroraRequestParser.java
> +    public static final String MELDINGID_FIELD = "Meldingsid";
Minor, men burde ikke feltet hete "MELDINGSID_FIELD"?  Det passer bedre med verdien og også språklig sett.

2022-01-12 13:40 UTC, RuneOfferdal commented on src/main/java/no/skatteetaten/aurora/mvc/AuroraHeaderRestTemplateCustomizer.java
> +    private String getKorrelasjonsid() {
Stusser på at man oppretter Korrelasjonsid to steder i koden (skjer også i AuroraRequestParser). Duplisering bør vel unngås.

2022-01-12 15:49 UTC, oyvinder approved these changes

2022-01-13 09:38 UTC, RuneOfferdal approved these changes

2022-01-13 10:47 UTC, merged