updated from maven to gradle
Skatteetaten/aurora-spring-boot-mvc-starter pull request #33
Opened 2022-06-30 11:14 UTC by jarlehansen

2022-07-01 10:43 UTC, bugge-jorgen requested changes
Enn hvor lange vi skal holde på med CHANGELOG. Du har glemt å oppdatere denne.

2022-08-02 08:04 UTC, oyvinder commented
Har verifisert at kotlin-dependencies ikke kommer med i Java-applikasjoner.

2022-08-02 08:06 UTC, oyvinder commented
Dependency org.osgi.core-6.0.0.jar kommer ikke med i gradle-bygg. Denne kom inn med gammel base starter

2022-08-02 08:43 UTC, oyvinder approved these changes

2022-08-09 08:53 UTC, RuneOfferdal approved these changes
Godkjent.  Har kommentert, men det er mer et spørsmål enn en korreksjon.

2022-08-09 08:53 UTC, RuneOfferdal commented on Jenkinsfile
> +    jacoco: false,
Jeg regner med at Jacoco ikke fungerer med Kotlin, eller noe slikt?

2022-08-10 05:44 UTC, jarlehansen commented on Jenkinsfile
> +    jacoco: false,
fikk ikke jacoco til å fungere, grafen bare viste 0

2022-08-11 09:02 UTC, merged